//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMG_PIAPS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("server=localhost;user id=root;password=root;persistsecurityinfo=True;database=mmg" +
            "mapiapsdb;")]
        public string CONSTR {
            get {
                return ((string)(this["CONSTR"]));
            }
            set {
                this["CONSTR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int MAIN_BUTTON_HEIGHT {
            get {
                return ((int)(this["MAIN_BUTTON_HEIGHT"]));
            }
            set {
                this["MAIN_BUTTON_HEIGHT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public int HIDE_TIMER {
            get {
                return ((int)(this["HIDE_TIMER"]));
            }
            set {
                this["HIDE_TIMER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>CASH RECEIPT</string>
  <string>BDO CURRENT ACCOUNT</string>
  <string>BPI CURRENT ACCOUNT</string>
  <string>LBP CURRENT ACCOUNT</string>
  <string>LBP MICRO ACCOUNT</string>
  <string>PNB CURRENT ACCOUNT</string>
  <string>PNB MICRO LENDING</string>
  <string>JOURNAL VOUCHER</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection PAID_UP_REFERENCE {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PAID_UP_REFERENCE"]));
            }
            set {
                this["PAID_UP_REFERENCE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50000")]
        public decimal MEMBER_CBU_LIMIT_TO_AVAIL_LOAN {
            get {
                return ((decimal)(this["MEMBER_CBU_LIMIT_TO_AVAIL_LOAN"]));
            }
            set {
                this["MEMBER_CBU_LIMIT_TO_AVAIL_LOAN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public decimal MEMBER_CBU_NOT_LOANABLE {
            get {
                return ((decimal)(this["MEMBER_CBU_NOT_LOANABLE"]));
            }
            set {
                this["MEMBER_CBU_NOT_LOANABLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int MIN_LATE_GRACE_PERIOD {
            get {
                return ((int)(this["MIN_LATE_GRACE_PERIOD"]));
            }
            set {
                this["MIN_LATE_GRACE_PERIOD"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("server=localhost;user id=root;password=root;persistsecurityinfo=True;database=mmg" +
            "mapiapsdb")]
        public string mmgmapiapsdbConnectionString {
            get {
                return ((string)(this["mmgmapiapsdbConnectionString"]));
            }
        }
    }
}
